import { ModelBuilder } from '../ModelBuilder';
import { GlobalScope } from '../ModelMetadata';
import { ModelMetadata } from '../ModelMetadata';

/**
 * Register one or more global scopes on a model class.
 * Scopes are applied automatically to every query executed by `ModelBuilder`.
 * Each scope is stored under a key equal to its constructor name.
 *
 * @example
 * ```ts
 * class PublishedScope implements Scope {
 *   apply(builder: ModelBuilder<any>): void {
 *     builder.whereNotNull('published_at');
 *   }
 * }
 *
 * \@scopedBy([PublishedScope])
 * \@table('posts')
 * class Post extends Model { ... }
 * ```
 */
export function scopedBy(scopes: (new () => GlobalScope)[]): ClassDecorator {
  return (target) => {
    const config = ModelMetadata.get(target);
    for (const ScopeClass of scopes) {
      config.globalScopes.set(ScopeClass.name, { scope: new ScopeClass() });
    }
  };
}

/**
 * Mark a model method as a **local scope** so it can be called fluently on any
 * query started from that model.
 *
 * The decorated method receives the `ModelBuilder` as its first argument, followed
 * by any additional parameters you pass at the call site.
 * The method should mutate the builder in place and return `void`.
 *
 * **Usage on the model:**
 * ```ts
 * \@table('users')
 * class User extends Model {
 *   \@scope
 *   popular(builder: ModelBuilder<User>): void {
 *     builder.where('votes', '>', 100);
 *   }
 *
 *   \@scope
 *   ofType(builder: ModelBuilder<User>, type: string): void {
 *     builder.where('type', type);
 *   }
 * }
 * ```
 *
 * **Calling scopes:**
 * ```ts
 * // Via the static helper generated by @scope:
 * const users = await User.popular().ofType('admin').get();
 *
 * // Via the query builder proxy:
 * const users = await User.query().popular().get();
 * ```
 */
export function scope(target: object, propertyKey: string, _descriptor: PropertyDescriptor): void {
  const ctor = (target as { constructor: Function }).constructor;
  const config = ModelMetadata.get(ctor);

  config.localScopes.set(
    propertyKey,
    function (this: unknown, builder: ModelBuilder<any>, ...args: unknown[]) {
      (_descriptor.value as Function).call(new (ctor as new () => unknown)(), builder, ...args);
    }
  );
}
